"use client";

import Link from "next/link";
import { useEffect,useState } from "react";
import { GitBranch, FileCode2, TriangleAlert, Unlink } from "lucide-react";
import { useProjectWorkspace } from "@/components/ProjectContext";
import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { apiGet, ImpactAnalysis, LineageGraph, ScriptFile } from "@/lib/api";

export default function Page(){const{projectId}=useProjectWorkspace();const[scripts,setScripts]=useState<ScriptFile[]>([]);const[impacts,setImpacts]=useState<ImpactAnalysis[]>([]);const[graph,setGraph]=useState<LineageGraph|null>(null);useEffect(()=>{if(!projectId)return;void Promise.all([apiGet<ScriptFile[]>(`/projects/${projectId}/scripts`),apiGet<ImpactAnalysis[]>(`/projects/${projectId}/lineage/impacts?limit=10`),apiGet<LineageGraph>(`/projects/${projectId}/lineage/graph?limit=200`)]).then(([a,b,c])=>{setScripts(a);setImpacts(b);setGraph(c);});},[projectId]);return <main><WorkspaceHeader title="脚本血缘与变更影响" meta="SQL / Shell 版本、字段血缘、差异与人工复核"/><div className="mx-auto max-w-7xl space-y-5 p-6"><div className="grid gap-4 md:grid-cols-4"><Card icon={FileCode2} label="脚本" value={scripts.length} href="/lineage/scripts"/><Card icon={GitBranch} label="血缘节点" value={graph?.nodes.length||0} href="/lineage/scripts"/><Card icon={TriangleAlert} label="未完成影响" value={impacts.filter(i=>i.status!=="reviewed").length} href="/lineage/changes"/><Card icon={Unlink} label="未解析" value={graph?.nodes.filter(i=>i.unresolved_flag).length||0} href="/lineage/unresolved"/></div><section className="panel p-4"><h2 className="font-semibold">安全边界</h2><p className="mt-2 text-sm text-slate-600">平台只读取和静态解析脚本，不执行 SQL、Shell、Git hooks 或仓库程序。高风险变化必须通过 impact_analysis → technical_review → final_review 才能重新标记 verified。</p></section><div className="grid gap-4 md:grid-cols-3"><Link className="panel p-5 hover:border-pine" href="/lineage/scripts"><strong>脚本仓库</strong><p className="mt-2 text-sm text-slate-500">上传 SQL / Shell / ZIP，配置受控 Git 同步。</p></Link><Link className="panel p-5 hover:border-pine" href="/lineage/changes"><strong>版本变化</strong><p className="mt-2 text-sm text-slate-500">查看文本、语义和血缘变化分类。</p></Link><Link className="panel p-5 hover:border-pine" href="/lineage/unresolved"><strong>人工解析绑定</strong><p className="mt-2 text-sm text-slate-500">多候选永不自动绑定。</p></Link></div></div></main>}
function Card({icon:Icon,label,value,href}:{icon:typeof GitBranch;label:string;value:number;href:string}){return <Link className="panel p-4" href={href}><Icon size={18}/><div className="mt-3 text-sm text-slate-500">{label}</div><div className="text-3xl font-semibold">{value}</div></Link>}
