"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";

import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { UatStatus, readError } from "@/components/uat/UatUi";
import { UatFinding, apiGet, apiPatch, apiPost } from "@/lib/api";
import { useProjectPermissions } from "@/lib/project-permissions";

export default function FindingPage(){const{findingId}=useParams<{findingId:string}>();const[item,setItem]=useState<UatFinding|null>(null);const[resolution,setResolution]=useState("");const[message,setMessage]=useState("");const permissions=useProjectPermissions(item?.project_id);async function load(){try{setItem(await apiGet<UatFinding>(`/uat-findings/${findingId}`));setMessage("")}catch(reason){setMessage(readError(reason))}}useEffect(()=>{void load()},[findingId]);async function assign(){try{await apiPatch(`/uat-findings/${findingId}`,{status:"assigned",assigned_role:"technical_analyst"});setMessage("已分派给技术分析角色");await load()}catch(reason){setMessage(readError(reason))}}async function resolve(){if(!resolution.trim()){setMessage("请填写解决说明");return}try{await apiPost(`/uat-findings/${findingId}/resolve`,{resolution_text:resolution.trim()});setMessage("Finding 已解决，等待验证");await load()}catch(reason){setMessage(readError(reason))}}async function verify(){try{await apiPost(`/uat-findings/${findingId}/verify`,{verification_comment:resolution.trim()||"复测通过"});setMessage("Finding 已验证关闭");await load()}catch(reason){setMessage(readError(reason))}}return <main><WorkspaceHeader title={item?`Finding #${item.finding_no}`:"Finding 详情"} meta={item?.title||"正在加载"}/><div className="mx-auto max-w-4xl space-y-5 p-4 lg:p-6">{message?<p className="panel p-3 text-sm">{message}</p>:null}{item?<><section className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="text-lg">{item.title}</b><p className="mt-1 text-sm text-slate-500">{item.finding_type} · {item.severity}</p></div><UatStatus value={item.status}/></div><p className="mt-4 whitespace-pre-wrap text-sm">{item.description}</p><dl className="mt-5 grid gap-4 text-sm md:grid-cols-2"><Field label="复现步骤" value={item.reproduction_steps}/><Field label="期望行为" value={item.expected_behavior}/><Field label="实际行为" value={item.actual_behavior}/><Field label="解决说明" value={item.resolution_text}/></dl></section>{permissions.can("uat.finding.manage")?<section className="panel space-y-3 p-4"><textarea className="control min-h-28" value={resolution} onChange={event=>setResolution(event.target.value)} placeholder="填写解决说明或验证意见"/><div className="flex flex-wrap gap-2">{item.status==="open"?<button className="button-secondary" onClick={assign}>分派技术处理</button>:null}{["open","assigned"].includes(item.status)?<button className="button-primary" onClick={resolve}>标记已解决</button>:null}{item.status==="resolved"?<button className="button-primary" onClick={verify}>验证通过</button>:null}</div></section>:null}</>:!message?<p className="panel p-5 text-sm text-slate-500">正在读取 Finding…</p>:null}</div></main>}
function Field({label,value}:{label:string;value?:string|null}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 whitespace-pre-wrap">{value||"-"}</dd></div>}
