"use client";

import { Play, RefreshCw } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

import { useProjectWorkspace } from "@/components/ProjectContext";
import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { UatMetric, UatStatus, readError } from "@/components/uat/UatUi";
import { UatRun, UatSuite, apiGet } from "@/lib/api";

export default function UatPage(){const{projectId}=useProjectWorkspace();const[suites,setSuites]=useState<UatSuite[]>([]);const[runs,setRuns]=useState<UatRun[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function load(){if(!projectId){setSuites([]);setRuns([]);return}setLoading(true);setError("");try{const[nextSuites,nextRuns]=await Promise.all([apiGet<UatSuite[]>(`/projects/${projectId}/uat-suites`),apiGet<UatRun[]>(`/projects/${projectId}/uat-runs`)]);setSuites(nextSuites);setRuns(nextRuns)}catch(reason){setError(readError(reason))}finally{setLoading(false)}}useEffect(()=>{void load()},[projectId]);const latest=runs[0];const summary=latest?.summary_json||{};return <main><WorkspaceHeader title="UAT 验收工作台" meta="套件、执行轮次、问题闭环与签署" actions={<button className="button-secondary" onClick={load}><RefreshCw size={15}/>刷新</button>}/><div className="mx-auto max-w-7xl space-y-5 p-4 lg:p-6">{!projectId?<p className="panel p-6 text-sm text-slate-500">请先选择一个项目。</p>:null}{error?<p className="panel border-red-200 p-4 text-sm text-red-700">{error}</p>:null}{projectId?<><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><UatMetric label="总 Case" value={summary.total_count||0}/><UatMetric label="通过" value={summary.passed_count||0}/><UatMetric label="失败" value={summary.failed_count||0}/><UatMetric label="阻断" value={summary.blocked_count||0}/><UatMetric label="待确认" value={summary.pending_count||0}/><UatMetric label="最近状态" value={latest?<UatStatusText value={latest.status}/>:"尚未执行"}/></section><section><h2 className="mb-3 font-semibold">测试套件</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{suites.map(item=><Link className="panel p-4 hover:border-pine" href={`/uat/suites/${item.id}`} key={item.id}><div className="flex justify-between gap-3"><b>{item.suite_name}</b><span className="text-xs text-slate-500">{item.cases.length} Cases</span></div><p className="mt-2 line-clamp-2 text-sm text-slate-500">{item.description||"未填写说明"}</p><span className="mt-3 inline-flex items-center gap-1 text-sm font-medium text-pine"><Play size={14}/>进入套件</span></Link>)}{!loading&&!suites.length?<p className="panel p-5 text-sm text-slate-500">暂无可用测试套件。</p>:null}</div></section><section><h2 className="mb-3 font-semibold">最近执行</h2><div className="panel divide-y divide-line">{runs.slice(0,20).map(item=><Link className="flex flex-wrap items-center justify-between gap-3 p-4 hover:bg-slate-50" href={`/uat/runs/${item.id}`} key={item.id}><div><b>{item.run_name}</b><div className="mt-1 text-xs text-slate-500">第 {item.run_no} 轮 · {item.environment_name}</div></div><UatStatus value={item.status}/></Link>)}{!loading&&!runs.length?<p className="p-5 text-sm text-slate-500">尚未执行 UAT。</p>:null}</div></section></>:null}{loading?<p className="text-sm text-slate-500">正在加载 UAT 状态…</p>:null}</div></main>}

function UatStatusText({value}:{value:string}){return <span className="text-base">{({passed:"通过",failed:"失败",blocked:"阻断",running:"执行中",queued:"排队中"}as Record<string,string>)[value]||value}</span>}
