"use client";
import { useEffect,useState } from "react";
import { DatabaseZap,Download,Search } from "lucide-react";
import { useProjectWorkspace } from "@/components/ProjectContext";
import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { CatalogColumn,CatalogSchema,CatalogSearchItem,CatalogTable,apiGet,apiPost } from "@/lib/api";

export default function CatalogPage(){
 const {projectId}=useProjectWorkspace();const [schemas,setSchemas]=useState<CatalogSchema[]>([]);const [tables,setTables]=useState<CatalogTable[]>([]);const [columns,setColumns]=useState<CatalogColumn[]>([]);const [selectedTable,setSelectedTable]=useState<number|null>(null);const [query,setQuery]=useState("");const [results,setResults]=useState<CatalogSearchItem[]>([]);const [message,setMessage]=useState("");
 useEffect(()=>{if(!projectId)return;void Promise.all([apiGet<CatalogSchema[]>(`/projects/${projectId}/catalog/schemas`),apiGet<{items:CatalogTable[]}>(`/projects/${projectId}/catalog/tables?page_size=100`)]).then(([s,t])=>{setSchemas(s);setTables(t.items);});},[projectId]);
 async function openTable(id:number){setSelectedTable(id);setColumns((await apiGet<{items:CatalogColumn[]}>(`/catalog/tables/${id}/columns?page_size=100`)).items);}
 async function search(){if(!projectId)return;const response=await apiPost<{items:CatalogSearchItem[]}>(`/projects/${projectId}/catalog/search`,{query,top_k:50});setResults(response.items);setMessage(`找到 ${response.items.length} 个目录字段`);}
 async function importColumn(id:number,type:"source"|"mart"){await apiPost(`/catalog/columns/${id}/import-as-${type}-field`,{});setMessage(type==="source"?"已导入来源层":"已导入监管集市层");await search();}
 return <main><WorkspaceHeader title="项目数据目录" meta={`${schemas.length} 个 schema / ${tables.length} 张已加载目录表`} /><div className="mx-auto max-w-[1600px] space-y-5 p-6"><section className="panel flex gap-2 p-4"><input className="control flex-1" onChange={e=>setQuery(e.target.value)} placeholder="搜索表名、字段名或中文注释" value={query}/><button className="button-primary" onClick={search}><Search size={16}/>搜索目录</button></section>{message?<p className="text-sm text-slate-600">{message}</p>:null}<div className="grid gap-5 xl:grid-cols-[220px_380px_1fr]"><section className="panel p-3"><h2 className="font-semibold">Schema 树</h2>{schemas.map(s=><div className="mt-2 text-sm" key={s.id}>{s.schema_name}</div>)}</section><section className="panel overflow-hidden"><div className="border-b p-3 font-semibold">表列表</div>{tables.map(t=><button className={`block w-full border-b p-3 text-left text-sm ${selectedTable===t.id?"bg-slate-100":""}`} key={t.id} onClick={()=>openTable(t.id)}><strong>{t.schema_name}.{t.table_name}</strong><div className="text-xs text-slate-500">{t.table_comment||t.table_type}</div></button>)}</section><section className="panel overflow-hidden"><div className="border-b p-3 font-semibold">字段（按表懒加载）</div>{(results.length?results:columns.map(c=>({catalog_column_id:c.id,datasource_id:c.datasource_id,datasource_name:"",schema_name:c.schema_name,table_name:c.table_name,column_name:c.column_name,column_comment:c.column_comment,data_type:c.data_type,nullable:c.nullable,is_primary_key:c.is_primary_key,score:0,match_reasons:[]}))).map(c=><div className="border-b p-3 text-sm" key={c.catalog_column_id}><div className="flex items-start justify-between gap-3"><div><strong>{c.table_name}.{c.column_name}</strong><div className="mt-1 text-slate-500">{c.column_comment||"无注释"} / {c.data_type||"类型未知"} / {c.nullable?"可空":"非空"}{c.is_primary_key?" / 主键":""}</div>{c.match_reasons?.length?<div className="mt-1 text-xs text-slate-500">评分 {Math.round(c.score*100)}% · {c.match_reasons.join("、")}</div>:null}</div><div className="flex gap-2"><button className="button-secondary" onClick={()=>importColumn(c.catalog_column_id,"source")}><Download size={14}/>来源层</button><button className="button-secondary" onClick={()=>importColumn(c.catalog_column_id,"mart")}><DatabaseZap size={14}/>集市层</button></div></div></div>)}</section></div></div></main>;
}
