"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { apiGet, apiPost } from "@/lib/api";

type Institution={id:number;institution_code:string;institution_name:string;institution_type:string;status:string};
export default function Page(){const[items,setItems]=useState<Institution[]>([]);const[msg,setMsg]=useState("");async function reload(){try{setItems(await apiGet("/admin/institutions"));}catch(error){setMsg(error instanceof Error?error.message:"加载失败");}}useEffect(()=>{void reload();},[]);async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{await apiPost("/admin/institutions",{institution_code:form.get("code"),institution_name:form.get("name"),institution_type:form.get("type")});event.currentTarget.reset();await reload();}catch(error){setMsg(error instanceof Error?error.message:"创建失败");}}return <main><WorkspaceHeader title="机构管理" meta="银行、咨询公司与平台运营机构"/><div className="mx-auto grid max-w-[1300px] gap-5 p-6 lg:grid-cols-[360px_1fr]"><form className="panel p-4" onSubmit={create}><input className="control" name="code" placeholder="机构代码" required/><input className="control mt-3" name="name" placeholder="机构名称" required/><select className="control mt-3" name="type"><option value="bank">银行</option><option value="consulting_company">咨询公司</option><option value="platform_operator">平台运营方</option></select><button className="button-primary mt-3 w-full">创建机构</button><div className="mt-4 flex gap-2"><Link className="button-secondary" href="/admin/users">用户</Link><Link className="button-secondary" href="/admin/permissions">权限矩阵</Link></div>{msg?<p className="mt-3 text-xs text-coral">{msg}</p>:null}</form><section className="panel divide-y divide-line">{items.map(item=><div className="flex items-center justify-between p-4" key={item.id}><div><b>{item.institution_name}</b><div className="text-xs text-slate-500">{item.institution_code} · {item.institution_type}</div></div><span className="rounded bg-emerald-50 px-2 py-1 text-xs text-emerald-700">{item.status}</span></div>)}</section></div></main>}
