"use client";

import { ArrowLeft, Check, Download, PlayCircle, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { useParams, useSearchParams } from "next/navigation";
import { Suspense, useEffect, useState } from "react";

import { useProjectWorkspace } from "@/components/ProjectContext";
import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { apiDownload, apiGet, apiPost, type TemplateDetail, type TemplateVersion } from "@/lib/api";
import { parentReturnHref } from "@/lib/navigation-contract.mjs";

type Diff={summary:{added:number;removed:number;modified:number};impact:{target_fields:number;scenarios:number;mappings:number};added:Change[];removed:Change[];modified:Change[]};
type Change={change_type:string;sheet_name:string;table_code:string;field_code:string;before?:Record<string,unknown>|null;after?:Record<string,unknown>|null;changed_values?:Record<string,{before:unknown;after:unknown}>};
type ParseResult={id:number;sheet_name:string;table_code?:string|null;table_name?:string|null;field_count:number;parsed_rows_json:Array<Record<string,unknown>>;warnings_json:string[]};
const STATUS:Record<string,string>={draft:"草稿",pending_review:"待审核",approved:"已审核",active:"已生效",superseded:"已替代",withdrawn:"已撤回"};
const format=(value?:string|null)=>value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"—";

export default function Page(){return <Suspense fallback={<p className="p-6">正在加载模板详情…</p>}><Detail/></Suspense>;}
function Detail(){
  const {templateId}=useParams<{templateId:string}>();const params=useSearchParams();const {projectId}=useProjectWorkspace();
  const id=Number(templateId);const [data,setData]=useState<TemplateDetail|null>(null),[selected,setSelected]=useState<number|null>(null),[diff,setDiff]=useState<Diff|null>(null),[parse,setParse]=useState<ParseResult[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const back=parentReturnHref("/templates",params.toString())||"/templates";
  async function load(){const next=await apiGet<TemplateDetail>(`/templates/${id}/detail`);setData(next);setSelected(current=>current&&next.versions.some(v=>v.id===current)?current:next.versions[0]?.id||null);}
  useEffect(()=>{if(Number.isFinite(id))void load();},[id]);
  useEffect(()=>{if(!selected)return;void Promise.all([apiGet<Diff>(`/templates/versions/${selected}/diff`),apiGet<ParseResult[]>(`/templates/${id}/parse-results?version_id=${selected}`)]).then(([d,p])=>{setDiff(d);setParse(p);});},[selected,id]);
  const version=data?.versions.find(item=>item.id===selected)||null;
  async function action(kind:"review"|"activate"|"apply") {if(!version)return;setBusy(true);setMessage("");try{if(kind==="apply")await apiPost(`/templates/${id}/apply`,{});else await apiPost(`/templates/versions/${version.id}/${kind}`,{});setMessage(kind==="review"?"版本已审核":kind==="activate"?"版本已激活，旧版本已标记为已替代":"已按当前生效版本 Apply，并写入审计变更集");await load();}catch(error){setMessage(error instanceof Error?error.message:"操作失败");}finally{setBusy(false);}}
  async function download(){if(!version)return;const {blob,fileName}=await apiDownload(`/templates/versions/${version.id}/content`);const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
  return <main><WorkspaceHeader title={data?.template.display_name||data?.template.file_name||"模板详情"} meta="监管版本与内部版本分别治理；激活后才允许 Apply。" actions={<Link className="button-secondary" href={back}><ArrowLeft size={16}/>返回模板列表</Link>}/>
    <div className="mx-auto max-w-6xl space-y-5 p-4 lg:p-6">{message?<p role="status" className="rounded-lg border border-line bg-white p-3 text-sm">{message}</p>:null}
      {!data?<p role="status">正在读取模板版本…</p>:<>
      <section className="panel p-5"><h2 className="font-semibold">模板概览</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-slate-500">稳定模板代码</dt><dd className="mt-1 font-medium">{data.template.template_code||"历史导入"}</dd></div><div><dt className="text-slate-500">当前生效内部版本</dt><dd className="mt-1 font-medium">{data.versions.find(v=>v.id===data.template.current_version_id)?.version_no?`内部版本 ${data.versions.find(v=>v.id===data.template.current_version_id)?.version_no}`:"尚未激活"}</dd></div><div><dt className="text-slate-500">版本数量</dt><dd className="mt-1 font-medium">{data.versions.length}</dd></div><div><dt className="text-slate-500">应用记录</dt><dd className="mt-1 font-medium">{data.applications.length}</dd></div></dl></section>
      <section className="panel overflow-hidden"><div className="panel-header"><h2 className="font-semibold">版本记录</h2></div><div className="divide-y divide-line">{data.versions.map(item=><button className={`grid w-full gap-2 p-4 text-left hover:bg-mist sm:grid-cols-[100px_1fr_1fr_130px] ${selected===item.id?"bg-amber-50":""}`} key={item.id} onClick={()=>setSelected(item.id)}><strong>内部版本 {item.version_no}</strong><span>监管版本：{item.regulatory_version||"未提供"}</span><span>{item.publisher||"发布机构未提供"} · {format(item.effective_at)}</span><span className={item.status==="active"?"badge-success":item.status==="pending_review"?"badge-warning":"badge-neutral"}>{STATUS[item.status]||item.status}</span></button>)}</div></section>
      {version?<><section className="panel p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">原始文件和解析结果</h2><p className="mt-1 text-sm text-slate-500">{version.file_name} · {version.sheet_names_json.length} 个 Sheet · 解析状态 {version.parse_status}</p></div><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={()=>void download()}><Download size={16}/>下载原始文件</button>{version.status==="pending_review"?<button className="button-primary" disabled={busy} onClick={()=>void action("review")}><ShieldCheck size={16}/>人工审核通过</button>:null}{version.status==="approved"?<button className="button-primary" disabled={busy} onClick={()=>void action("activate")}><PlayCircle size={16}/>激活生效</button>:null}{version.status==="active"?<button className="button-primary" disabled={busy} onClick={()=>void action("apply")}><Check size={16}/>Apply 当前版本</button>:null}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{parse.map(sheet=><article className="rounded-lg border border-line p-4" key={sheet.id}><h3 className="font-medium">{sheet.sheet_name}</h3><p className="mt-1 text-sm text-slate-600">{sheet.table_code||"无表代码"} · {sheet.table_name||"无表名称"} · {sheet.field_count} 个字段</p>{sheet.warnings_json.length?<p className="mt-2 text-xs text-amber-700">{sheet.warnings_json.join("；")}</p>:null}</article>)}</div></section>
      <section className="panel p-5"><h2 className="font-semibold">版本差异</h2>{diff?<><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="stat-card"><span className="stat-label">新增字段</span><strong>{diff.summary.added}</strong></div><div className="stat-card"><span className="stat-label">删除字段</span><strong>{diff.summary.removed}</strong></div><div className="stat-card"><span className="stat-label">修改字段</span><strong>{diff.summary.modified}</strong></div></div><p className="mt-4 text-sm">影响范围：目标字段 {diff.impact.target_fields} · 场景 {diff.impact.scenarios} · 映射 {diff.impact.mappings}</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b"><th className="p-2">变化</th><th>Sheet / 表 / 字段</th><th>修改前</th><th>修改后</th></tr></thead><tbody>{[...diff.added,...diff.removed,...diff.modified].map((item,index)=><tr className="border-b align-top" key={`${item.change_type}-${item.field_code}-${index}`}><td className="p-2">{item.change_type==="added"?"新增":item.change_type==="removed"?"删除":"修改"}</td><td>{item.sheet_name} / {item.table_code} / {item.field_code}</td><td className="max-w-64 whitespace-pre-wrap break-words">{JSON.stringify(item.changed_values?Object.fromEntries(Object.entries(item.changed_values).map(([k,v])=>[k,v.before])):item.before,null,2)}</td><td className="max-w-64 whitespace-pre-wrap break-words">{JSON.stringify(item.changed_values?Object.fromEntries(Object.entries(item.changed_values).map(([k,v])=>[k,v.after])):item.after,null,2)}</td></tr>)}</tbody></table>{!diff.added.length&&!diff.removed.length&&!diff.modified.length?<p className="py-4 text-sm text-slate-500">首个版本或未发现字段差异。</p>:null}</div></>:<p>正在计算差异…</p>}</section></>:null}
      <section className="panel p-5"><h2 className="font-semibold">应用记录和影响范围</h2>{data.applications.length?<div className="mt-4 space-y-3">{data.applications.map(item=><article className="rounded-lg border border-line p-4" key={item.id}><p className="font-medium">应用记录 #{item.id} · 来源版本 {data.versions.find(v=>v.id===item.template_version_id)?.version_no||"历史导入"}</p><p className="mt-1 text-sm text-slate-600">{format(item.applied_at)} · 影响表 {item.impact_json.tables||0} · 字段 {item.impact_json.fields||0} · 变更 {item.change_set_json.length}</p></article>)}</div>:<p className="mt-3 text-sm text-slate-500">尚未 Apply，没有影响现有目标字段。</p>}</section>
      </>}</div></main>;
}
