"use client";
import { FormEvent,useEffect,useState } from "react";
import { RefreshCw,Upload } from "lucide-react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { DataSource,MetadataSyncTask,apiGet,apiPost,uploadForm } from "@/lib/api";

export default function DatasourceCatalogPage(){const id=Number(useParams<{datasourceId:string}>().datasourceId);const [datasource,setDatasource]=useState<DataSource|null>(null);const [tasks,setTasks]=useState<MetadataSyncTask[]>([]);const [message,setMessage]=useState("");async function reload(){const [ds,items]=await Promise.all([apiGet<DataSource>(`/datasources/${id}`),apiGet<MetadataSyncTask[]>(`/datasources/${id}/metadata-sync-tasks`)]);setDatasource(ds);setTasks(items);}useEffect(()=>{if(id)void reload();},[id]);async function sync(){try{const result=await apiPost<MetadataSyncTask>(`/datasources/${id}/metadata-sync`,{sync_mode:"full",schema_names:[],include_views:true});setMessage(`同步 ${result.status}：${result.table_count} 表 / ${result.column_count} 字段`);await reload();}catch(error){setMessage(error instanceof Error?error.message:"同步失败");}}async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);try{const result=await uploadForm<{id:number;parse_summary_json:{row_count:number}}>(`/datasources/${id}/metadata-import/upload`,form);setMessage(`数据字典预览 ${result.parse_summary_json.row_count} 行，确认后 apply`);await apiPost(`/metadata-imports/${result.id}/apply`,{});setMessage(`数据字典 ${result.parse_summary_json.row_count} 行已 apply`);}catch(error){setMessage(error instanceof Error?error.message:"导入失败");}}return <main><WorkspaceHeader title={`${datasource?.name||"数据源"} 元数据目录`} meta="元数据采集不读取业务表明细"/><div className="mx-auto max-w-5xl space-y-5 p-6"><section className="panel flex flex-wrap gap-3 p-4"><button className="button-primary" onClick={sync}><RefreshCw size={16}/>同步元数据</button><Link className="button-secondary" href="/catalog">查看项目目录</Link><form className="flex gap-2" onSubmit={upload}><input accept=".xlsx" className="control" name="file" required type="file"/><button className="button-secondary"><Upload size={16}/>上传数据字典</button></form></section>{message?<p className="text-sm text-slate-600">{message}</p>:null}<section className="panel overflow-hidden"><div className="border-b p-3 font-semibold">最近同步状态</div>{tasks.map(task=><div className="border-b p-3 text-sm" key={task.id}><strong>{task.status}</strong> · {task.schema_count} schema / {task.table_count} 表 / {task.column_count} 字段{task.warnings_json.length?<div className="text-amber-700">{task.warnings_json.join("；")}</div>:null}</div>)}</section></div></main>}
