"use client";

import { Copy, Play } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import { WorkspaceHeader } from "@/components/WorkspaceHeader";
import { UatStatus, readError } from "@/components/uat/UatUi";
import { UatRun, UatSuite, apiGet, apiPost } from "@/lib/api";
import { useProjectPermissions } from "@/lib/project-permissions";

export default function SuitePage(){const{suiteId}=useParams<{suiteId:string}>();const router=useRouter();const[suite,setSuite]=useState<UatSuite|null>(null);const[name,setName]=useState("");const[message,setMessage]=useState("");const permissions=useProjectPermissions(suite?.project_id);useEffect(()=>{apiGet<UatSuite>(`/uat-suites/${suiteId}`).then(setSuite).catch(reason=>setMessage(readError(reason)))},[suiteId]);async function createRun(){if(!suite)return;try{const run=await apiPost<UatRun>(`/uat-suites/${suite.id}/runs`,{run_name:name.trim()||`${suite.suite_name} 验收轮次`,environment_name:"uat",application_version:null,git_commit_sha:null});router.push(`/uat/runs/${run.id}`)}catch(reason){setMessage(readError(reason))}}async function clone(){if(!suite)return;try{const item=await apiPost<UatSuite>(`/uat-suites/${suite.id}/clone`,{suite_name:`${suite.suite_name} 自定义副本`});router.push(`/uat/suites/${item.id}`)}catch(reason){setMessage(readError(reason))}}return <main><WorkspaceHeader title={suite?.suite_name||"UAT 套件"} meta={suite?`${suite.cases.length} 个测试案例 · ${suite.suite_type}`:"正在加载"}/><div className="mx-auto max-w-6xl space-y-5 p-4 lg:p-6">{message?<p className="panel p-3 text-sm">{message}</p>:null}{suite&&permissions.can("uat.execute")?<section className="panel flex flex-wrap gap-3 p-4"><input className="control min-w-64 flex-1" value={name} onChange={event=>setName(event.target.value)} placeholder="本轮 UAT 名称"/><button className="button-primary" onClick={createRun}><Play size={15}/>创建执行轮次</button>{permissions.can("uat.manage")?<button className="button-secondary" onClick={clone}><Copy size={15}/>复制为自定义套件</button>:null}</section>:null}<section className="space-y-3">{suite?.cases.map(item=><article className="panel p-4" key={item.id}><div className="flex flex-wrap items-center justify-between gap-2"><div><span className="mr-2 text-xs text-slate-400">{item.case_code}</span><b>{item.case_name}</b></div><div className="flex gap-2"><UatStatus value={item.execution_mode==="automatic"?"queued":"pending"}/><span className="rounded bg-slate-100 px-2 py-1 text-xs">{item.severity}</span></div></div><p className="mt-2 text-sm text-slate-500">{item.description||"未填写说明"}</p></article>)}</section>{!suite&&!message?<p className="panel p-5 text-sm text-slate-500">正在读取套件…</p>:null}</div></main>}
