"use client";

import { ChevronDown, ChevronRight } from "lucide-react";

import { SemanticLifecycle } from "@/components/semantic-catalog/SemanticStatus";
import { sortSemanticVersions } from "@/lib/semantic-catalog-view-model.mjs";
import type { SemanticDetailVersion, SemanticVersionRegion } from "@/lib/semantic-catalog-view-model.mjs";

export function VersionTimeline({ region, selectedVersion, onVersion }: {region:SemanticVersionRegion;selectedVersion:number|null;onVersion:(version:number|null)=>void}) {
  const versions = sortSemanticVersions([...region.confirmed, ...region.candidates, ...region.audit]);
  return <section aria-labelledby="version-timeline-heading"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-base font-semibold text-ink" id="version-timeline-heading">版本时间线</h2><span className="text-xs text-slate-500">从旧到新 · {versions.length} 个版本</span></div><ol className="mt-4 border-l border-line pl-5">{versions.map((version) => <VersionItem audit={region.audit.some((item) => item.id === version.id)} currentId={region.current_effective_version_id ?? null} effectiveId={region.effective_version_id ?? null} expanded={selectedVersion === version.id} key={version.id} onToggle={() => onVersion(selectedVersion === version.id ? null : version.id)} version={version} />)}</ol></section>;
}
function VersionItem({ version, expanded, audit, effectiveId, currentId, onToggle }: {version:SemanticDetailVersion;expanded:boolean;audit:boolean;effectiveId:number|null;currentId:number|null;onToggle:()=>void}) { const selectedDate = !audit && version.status === "confirmed" && version.id === effectiveId; const current = !audit && version.status === "confirmed" && version.id === currentId; const panelId = `semantic-version-panel-${version.id}`; return <li className="relative border-b border-line py-3 before:absolute before:-left-[25px] before:top-5 before:h-2 before:w-2 before:rounded-full before:bg-pine-500"><button aria-controls={panelId} aria-expanded={expanded} className="flex min-h-11 w-full items-start gap-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pine-500/30" onClick={onToggle} type="button">{expanded ? <ChevronDown aria-hidden className="mt-1 shrink-0" size={16} /> : <ChevronRight aria-hidden className="mt-1 shrink-0" size={16} />}<span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm text-ink">v{version.version_no}</span><SemanticLifecycle status={version.status} />{selectedDate ? <span className="badge-info">所选日期生效</span> : null}{current ? <span className="badge-success">当前生效</span> : null}{audit ? <span className="text-xs text-coral-700">非当前事实</span> : null}</span><span className="mt-1 block font-mono text-xs text-slate-500">{version.effective_from} → {version.effective_to || "当前"}</span></span></button>{expanded ? <article className="ml-7 mt-3 space-y-3 rounded-lg border border-line bg-white p-4" id={panelId}><h3 className="text-sm font-semibold text-ink">{version.concept_name}</h3><p className="whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{version.definition || "未提供定义文本。"}</p><dl className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><Item label="来源" value={`${version.source_type}${version.source_id ? ` #${version.source_id}` : ""}`} /><Item label="置信等级" value={version.confidence_level} /><Item label="确认人 / 时间" value={`${version.confirmed_by || "未记录"} / ${version.confirmed_at || "未记录"}`} /></dl></article> : null}</li>; }
function Item({label,value}:{label:string;value:string}) { return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 break-words text-slate-700">{value}</dd></div>; }
