SELECT
    CUSTOMER_ID,
    ACCOUNT_ID,
    ACCOUNT_NAME,
    PRODUCT_CODE,
    CURRENCY_CODE,
    END_OF_DAY_BALANCE,
    OPEN_DATE,
    STATUS_CODE,
    BRANCH_CODE,
    REPORT_DATE
FROM DEMO_CORE.DEMO_ACCOUNT_INFO
WHERE REPORT_DATE = '${REPORT_DATE}';
